// The committed setup context (`.rca-context.json`) — find, read, select a
// profile, and write one connector at a time.
//
// THREE THINGS THIS FILE DELIBERATELY DOES NOT DO.
//
// 1. It does not harden what it writes. Every other persisted artifact in lib/
//    (csv-state, evidence-file, turn1-registry, tool-cache) creates 0700
//    directories and 0600 files, and state-dir sweeps the tree to match. That is
//    right for OS-temp run state and wrong for this one: the context is
//    git-tracked, git does not preserve the mode, and a 0600 file inside a repo
//    is a confusing artifact rather than a protected one. `hardenStateDir` must
//    never be pointed here, and there is no chmod below.
//
// 2. It does not detect credentials. There is no looksLikeSecret, no entropy
//    check, no provider-prefix table, no pattern over content. Deciding whether
//    a string is a secret is a judgement, and the four times this project
//    encoded that judgement in a pattern it broke. What replaces it is shape:
//    `credential` is only {kind:"env-var", name} or {kind:"provider-managed"},
//    every closed object below validates its keys against an allowlist, and the
//    schema has no field a value belongs in. The rest is prompt discipline in
//    skills/rca-build/references/interview.md.
//
// 3. It never executes `howToQuery`. That field is stored structured
//    ({tool, args[]}) as DOCUMENTATION: the agent reads it and re-authors its own
//    call under the user's permission layer. If this module shelled it, a PR
//    editing a file reviewers skim as config would change what commands run. The
//    only child_process use here is the `git` needed to resolve worktrees and
//    tracked-ness.
//
// Dates are always injected (`todayISO`). Nothing below reads the clock, so
// selection and staleness are deterministic in tests and usable from the
// auto-mode sandbox.

import { execFileSync } from "node:child_process";
import {
  readFileSync, readdirSync, realpathSync, renameSync, statSync, unlinkSync, writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";

/** Deliberately NOT under `.rca/`, which holds per-run state and is gitignored by
 *  convention — a context placed there would trip the check-ignore guard below
 *  and refuse to persist. */
export const CONTEXT_FILENAME = ".rca-context.json";

export const SCHEMA_VERSION = 1;

/** The one capability a run cannot proceed without: without the code and the
 *  merged PRs there is no culprit PR, which is the run's entire deliverable.
 *  "Runnable" and "this capability is verified" are the same predicate. */
export const MANDATORY_CAPABILITY = "github";

/** Only relabels a digest line from `verified` to `stale`. Never blocks, never
 *  asks anything by itself. Overridden by config `context.staleAfterDays`. */
export const DEFAULT_STALE_AFTER_DAYS = 30;

/** How a credential is REFERENCED. There is no kind that carries a value. */
export const CREDENTIAL_KIND = {
  /** The customer exports it; only the variable's NAME is ever persisted. */
  ENV_VAR: "env-var",
  /** A forge CLI holding its own keyring/device-flow token has no variable to
   *  name. Without this kind a teammate is told to export something the first
   *  engineer never used. */
  PROVIDER_MANAGED: "provider-managed",
};

/** Stamped into a fresh document so nobody hand-writes the explanation. */
export const CONTEXT_README =
  "Generated by the RCA plugin's setup interview. Commit it — teammates inherit it " +
  "and are asked only for credentials. Credential VALUES never belong in this file; " +
  "reference them by env-var NAME.";

const REQUIRED_FIELDS = ["schemaVersion", "homeRepo", "profiles"];

// Closed key sets. This is the whole of the "no field a secret belongs in"
// guarantee: an unknown key is refused rather than persisted, so a `value`,
// `token` or captured-output field cannot be smuggled into a closed object.
// `scope` is the one deliberate exception — its keys are the customer's tool's
// vocabulary. A fixed list there is exactly how one vendor's terms once shipped
// as this project's schema field names, locking out every other stack.
const CONTEXT_KEYS = new Set(["_README", "schemaVersion", "homeRepo", "defaultProfile", "profiles"]);
const PROFILE_KEYS = new Set([
  "buildMatch", "repos", "subpaths", "branches", "connectors", "gaps", "warnings",
]);
const REPO_ROLES = new Set(["product", "automation"]);
const BRANCH_KEYS = new Set(["default", "observed"]);
const CONNECTOR_KEYS = new Set(["via", "scope", "howToQuery", "credential", "verifiedBy", "verifiedAt"]);
const HOW_TO_QUERY_KEYS = new Set(["tool", "args"]);
const CREDENTIAL_KEYS = new Set(["kind", "name"]);
const VERIFIED_BY_KEYS = new Set(["count", "observedAt", "note"]);
const GAP_KEYS = new Set(["capability", "classification", "note", "target"]);

/** How far up to walk. Guessing harder risks reading an unrelated checkout,
 *  which is silently wrong rather than merely slow. */
const MAX_LEVELS = 3;

// ---- character classes, so nothing here needs a pattern --------------------

const DIGITS = "0123456789";
const UPPER = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const LOWER = "abcdefghijklmnopqrstuvwxyz";

function allDigits(s) {
  if (s.length === 0) return false;
  for (const ch of s) if (!DIGITS.includes(ch)) return false;
  return true;
}

function isPlainObject(v) {
  return v !== null && typeof v === "object" && !Array.isArray(v);
}

function isNonEmptyString(v) {
  return typeof v === "string" && v.trim() !== "";
}

function isStringArray(v) {
  return Array.isArray(v) && v.every((x) => typeof x === "string");
}

function trimChar(s, ch) {
  let a = 0;
  let b = s.length;
  while (a < b && s[a] === ch) a++;
  while (b > a && s[b - 1] === ch) b--;
  return s.slice(a, b);
}

/**
 * A calendar day, `YYYY-MM-DD`, optionally followed by `T…` so a full ISO
 * timestamp someone pastes in is still readable. Day precision is the storage
 * format on purpose: millisecond precision guarantees a merge conflict every
 * time a teammate writes.
 *
 * Character arithmetic rather than a pattern — see the header.
 */
export function isISODate(value) {
  if (typeof value !== "string") return false;
  if (value.length !== 10 && !(value.length > 10 && value[10] === "T")) return false;
  const day = value.slice(0, 10);
  if (day[4] !== "-" || day[7] !== "-") return false;
  const y = day.slice(0, 4);
  const m = day.slice(5, 7);
  const d = day.slice(8, 10);
  if (!allDigits(y) || !allDigits(m) || !allDigits(d)) return false;
  const month = Number(m);
  const dayNum = Number(d);
  return month >= 1 && month <= 12 && dayNum >= 1 && dayNum <= 31;
}

/**
 * Does this look like an environment-variable identifier? Character-class
 * arithmetic, and it is a NAME check only — this function never sees a value,
 * because the interview never asks for one.
 */
export function isEnvVarName(name) {
  if (typeof name !== "string" || name.length === 0 || name.length > 128) return false;
  const first = name[0];
  if (!(UPPER.includes(first) || LOWER.includes(first) || first === "_")) return false;
  for (const ch of name) {
    if (!(UPPER.includes(ch) || LOWER.includes(ch) || DIGITS.includes(ch) || ch === "_")) return false;
  }
  return true;
}

function utcDay(day) {
  return Date.UTC(Number(day.slice(0, 4)), Number(day.slice(5, 7)) - 1, Number(day.slice(8, 10)));
}

/** Whole days from `fromISO` to `toISO`. `Date.UTC` used as a calendar function;
 *  no clock is read. */
function daysBetween(fromISO, toISO) {
  if (!isISODate(fromISO) || !isISODate(toISO)) return null;
  return Math.floor((utcDay(toISO.slice(0, 10)) - utcDay(fromISO.slice(0, 10))) / 86400000);
}

// ---- the two predicates ----------------------------------------------------

/**
 * Does this `verifiedBy` carry a decidable claim?
 *
 * THE SHAPE IS THE POINT. `verifiedBy` must hold a `count` (an integer — zero is
 * legitimate: a reachable-but-empty PR window is a warning, not a failure) or an
 * `observedAt` day. A `note` alone is not verification.
 *
 * A non-empty-string check here would be satisfied by `"TODO"` and by
 * `"attempted, could not list PRs"` — both of which an agent hedging instead of
 * failing will write. That is this project's own recurring defect one level up:
 * a recorded "check" naming a tool's version banner, which satisfied a presence
 * check while proving nothing about whether the credential could see the target.
 * The lifecycle boundary of the whole feature rests on this function, so it is a
 * shape check with no judgement in it at all.
 */
function isVerifiedClaim(verifiedBy) {
  if (!isPlainObject(verifiedBy)) return false;
  if (Number.isInteger(verifiedBy.count) && verifiedBy.count >= 0) return true;
  return isISODate(verifiedBy.observedAt);
}

/**
 * PREDICATE 1 — gates the run.
 *
 * A profile is runnable iff `connectors.github` exists and its `verifiedBy`
 * carries a `count` or an `observedAt`. Nothing else is consulted: no `complete`
 * flag exists, because the absence of a verified mandatory connector IS the
 * marker, which is what makes an abandoned interview resumable for free.
 */
export function isRunnable(profile) {
  const connector = profile?.connectors?.[MANDATORY_CAPABILITY];
  if (!isPlainObject(connector)) return false;
  return isVerifiedClaim(connector.verifiedBy);
}

/**
 * The capability sequence, derived from config rather than restated in code.
 * `config/rca.config.json`'s `evidenceRouting` already names the set; an entry
 * TFA owns (`skip: true`) contributes nothing for us to provision.
 *
 * `fallbackCapability` is deliberately NOT folded in here: a capability served
 * only by another one's connector is still un-answered as far as setup is
 * concerned, and the resolution is to record a gap — which is a write, visible in
 * the file, rather than an inference nobody can see.
 */
/**
 * Which capability covers which, when the customer has no dedicated connector.
 *
 * `{ci: "github"}` for the shipped config. Read from the same place the sequence
 * is, so adding a fallback in config is enough — nothing here needs editing.
 */
export function capabilityFallbacks(config) {
  const routing = config?.evidenceRouting;
  const out = {};
  if (!isPlainObject(routing)) return out;
  for (const entry of Object.values(routing)) {
    if (!isPlainObject(entry) || entry.skip === true) continue;
    const { capability, fallbackCapability: fb } = entry;
    if (!isNonEmptyString(capability) || !isNonEmptyString(fb) || fb === capability) continue;
    out[capability] = fb;
  }
  return out;
}

export function capabilitySequence(config) {
  const routing = config?.evidenceRouting;
  const out = [];
  if (!isPlainObject(routing)) return out;
  for (const entry of Object.values(routing)) {
    if (!isPlainObject(entry) || entry.skip === true) continue;
    const capability = entry.capability;
    if (!isNonEmptyString(capability) || out.includes(capability)) continue;
    out.push(capability);
  }
  return out;
}

/**
 * Capabilities with neither a connector nor a gap, in sequence order.
 *
 * This is the reader `provisioned` needed and the earlier draft lacked: the first
 * element IS the resume point (walk the sequence, resume at the first capability
 * with neither), so nothing has to be stored to resume an interrupted interview.
 * A skip writes a gap, so a skipped capability is never re-asked.
 */
export function missingCapabilities(profile, capabilities = [], fallbacks = {}) {
  const connectors = isPlainObject(profile?.connectors) ? profile.connectors : {};
  const gapped = new Set();
  for (const gap of Array.isArray(profile?.gaps) ? profile.gaps : []) {
    if (isNonEmptyString(gap)) gapped.add(gap);
    else if (isNonEmptyString(gap?.capability)) gapped.add(gap.capability);
  }

  // A capability whose FALLBACK has a connector is covered, and asking about it
  // again would be asking a question whose answer we already have.
  //
  // Without this, `ci` is a trap: for every team whose CI is their git forge there
  // is no separate system to record, so `ci` gets no connector — and the only way
  // to become provisioned would be to record a GAP on a capability that demonstrably
  // works, because buildManifest's fallback is already serving it. The gate would
  // then either offer to resume a finished interview on every run, or print "ci
  // unavailable" about a working connector. Neither is true, so neither is written.
  //
  // Single hop, matching buildManifest: the fallback must have a connector of its
  // own, never another fallback.
  const covered = (c) =>
    Object.hasOwn(connectors, c) ||
    gapped.has(c) ||
    (isNonEmptyString(fallbacks?.[c]) && Object.hasOwn(connectors, fallbacks[c]));

  return capabilities.filter((c) => !covered(c));
}

/**
 * PREDICATE 2 — gates whether the gate OFFERS to resume, never the run itself.
 *
 * Runnable is not the same as finished, and conflating them locks a customer in:
 * the mandatory capability is asked first, so someone who abandons straight after
 * it has a runnable profile, first contact never fires again, and every later run
 * quietly declares the rest unavailable to TFA. A profile that is runnable but
 * not provisioned spends the gate's single question on "finish setup now, or run
 * with the rest recorded as gaps?" — and answering it writes those gaps, so it is
 * asked exactly once.
 */
export function isProvisioned(profile, capabilities = [], fallbacks = {}) {
  return missingCapabilities(profile, capabilities, fallbacks).length === 0;
}

// ---- profile matching: no regex, anchored, one wildcard --------------------

/**
 * Case-folded, WHOLE-STRING match with at most one `*`, built from
 * startsWith/endsWith. No regex anywhere near it.
 *
 * Anchoring is the load-bearing part: substring matching makes the pattern
 * `nightly` match the build `web-nightly-42`, and a wrong profile means a run
 * against another environment's repos and branches — a confident wrong answer
 * rather than a gap.
 *
 * Two or more wildcards do not match. A pattern that ambiguous cannot be
 * persisted (validateContext refuses it), so this only guards a hand-edited file,
 * and "no match" there surfaces as a refusal to select rather than a guess.
 *
 * Matches the build NAME, never the id: an id is unique, so the only pattern that
 * could match one is `*`.
 */
export function matchesBuildName(pattern, buildName) {
  if (typeof pattern !== "string" || typeof buildName !== "string") return false;
  const p = pattern.toLowerCase();
  const n = buildName.toLowerCase();
  const star = p.indexOf("*");
  if (star === -1) return p === n;
  if (p.indexOf("*", star + 1) !== -1) return false;
  const head = p.slice(0, star);
  const tail = p.slice(star + 1);
  if (n.length < head.length + tail.length) return false;
  return n.startsWith(head) && n.endsWith(tail);
}

/** Literal characters in a pattern — the tie-breaker between two matches. */
function specificityOf(pattern) {
  let literal = 0;
  for (const ch of String(pattern)) if (ch !== "*") literal++;
  return literal;
}

function stalenessOf(profile, todayISO, staleAfterDays) {
  const stale = [];
  const ages = {};
  if (!isISODate(todayISO)) return { stale, ages };
  for (const [capability, connector] of Object.entries(profile?.connectors ?? {})) {
    const day = isISODate(connector?.verifiedAt)
      ? connector.verifiedAt
      : isISODate(connector?.verifiedBy?.observedAt)
        ? connector.verifiedBy.observedAt
        : null;
    if (day === null) continue;
    const age = daysBetween(day, todayISO);
    if (age === null) continue;
    ages[capability] = age;
    if (age > staleAfterDays) stale.push(capability);
  }
  return { stale, ages };
}

/**
 * Pick the profile this run uses. First hit wins, and every refusal names what it
 * would have had to guess.
 *
 *   1. `requested` → EXACT key match, else refuse listing the labels. No fuzzy
 *      match: a typo resolving to a neighbouring label is a wrong-context run.
 *   2. `buildName` → profiles whose `buildMatch` matches it.
 *   3. Several candidates → most literal characters wins; an exact tie REFUSES,
 *      naming both. Never alphabetical, never first-key-in-file — JSON key order
 *      is a hidden ordering a reformat silently changes. Even when specificity
 *      resolves it the result carries `alsoMatched`, which is how the file gets
 *      fixed.
 *   4. Zero candidates for a KNOWN build name → one profile in the file: use it
 *      and say so; more than one: refuse. `defaultProfile` is deliberately not
 *      consulted here — a name matching nothing means the file does not describe
 *      this build.
 *   5. Build name genuinely unknown → `defaultProfile`. Its only job.
 *   6. The selection must then be runnable. If it is not, REFUSE — never silently
 *      switch to a runnable sibling. That is the wrong-context run in its purest
 *      form.
 *
 * Staleness is evaluated last and never blocks: it only labels.
 */
export function selectProfile({
  context,
  buildName = null,
  requested = null,
  todayISO = null,
  staleAfterDays = DEFAULT_STALE_AFTER_DAYS,
} = {}) {
  const profiles = context?.profiles;
  if (!isPlainObject(profiles) || Object.keys(profiles).length === 0) {
    return {
      ok: false,
      code: "no-profiles",
      labels: [],
      message: "this context declares no profiles, so there is nothing to select — re-run first contact",
    };
  }
  const labels = Object.keys(profiles);
  let label = null;
  let matchedBy = null;
  let alsoMatched = [];

  if (isNonEmptyString(requested)) {
    const want = requested.trim();
    if (!Object.hasOwn(profiles, want)) {
      return {
        ok: false,
        code: "unknown-profile",
        labels,
        requested: want,
        message:
          `no profile named '${want}' in this context (have: ${labels.join(", ")}). Labels are matched ` +
          `exactly — a near miss would run against another environment's repos, so it is refused.`,
      };
    }
    label = want;
    matchedBy = "requested";
  } else if (isNonEmptyString(buildName)) {
    const scored = [];
    for (const candidate of labels) {
      const patterns = Array.isArray(profiles[candidate]?.buildMatch) ? profiles[candidate].buildMatch : [];
      let best = -1;
      for (const pattern of patterns) {
        if (matchesBuildName(pattern, buildName)) best = Math.max(best, specificityOf(pattern));
      }
      if (best >= 0) scored.push({ label: candidate, specificity: best });
    }
    if (scored.length === 0) {
      if (labels.length === 1) {
        label = labels[0];
        matchedBy = "sole-profile";
      } else {
        return {
          ok: false,
          code: "no-matching-profile",
          labels,
          buildName,
          message:
            `no profile's buildMatch matches build '${buildName}', and this context holds ${labels.length} ` +
            `profiles (${labels.join(", ")}). defaultProfile is deliberately NOT used here: a build name ` +
            `matching nothing means the file does not describe this build. Add a buildMatch pattern, or ` +
            `re-run with an explicit profile.`,
        };
      }
    } else {
      const top = Math.max(...scored.map((s) => s.specificity));
      const winners = scored.filter((s) => s.specificity === top);
      if (winners.length > 1) {
        return {
          ok: false,
          code: "ambiguous-profile",
          labels: winners.map((w) => w.label),
          buildName,
          message:
            `build '${buildName}' matches ${winners.map((w) => `'${w.label}'`).join(" and ")} with equal ` +
            `specificity (${top} literal characters each). Refusing rather than picking one: neither ` +
            `alphabetical order nor JSON key order is a decision anybody made. Narrow one pattern, or ` +
            `re-run with an explicit profile.`,
        };
      }
      label = winners[0].label;
      matchedBy = "build-name";
      alsoMatched = scored.filter((s) => s.label !== label).map((s) => s.label);
    }
  } else {
    const fallback = context?.defaultProfile;
    if (isNonEmptyString(fallback)) {
      if (!Object.hasOwn(profiles, fallback)) {
        return {
          ok: false,
          code: "unknown-default-profile",
          labels,
          requested: fallback,
          message: `defaultProfile names '${fallback}', which is not a profile in this file (have: ${labels.join(", ")})`,
        };
      }
      label = fallback;
      matchedBy = "default-profile";
    } else if (labels.length === 1) {
      label = labels[0];
      matchedBy = "sole-profile";
    } else {
      return {
        ok: false,
        code: "no-default-profile",
        labels,
        message:
          `no build name was given and this context sets no defaultProfile, so there is no way to choose ` +
          `between ${labels.join(", ")}. Set defaultProfile, or re-run with an explicit profile.`,
      };
    }
  }

  const profile = profiles[label];
  if (!isRunnable(profile)) {
    return {
      ok: false,
      code: "not-runnable",
      label,
      labels,
      matchedBy,
      message:
        `profile '${label}' has no verified '${MANDATORY_CAPABILITY}' connector — its verifiedBy carries ` +
        `neither a count nor an observedAt, so nothing proves a live read ever succeeded. Refusing rather ` +
        `than switching to a runnable sibling: a run against another profile's repos and branches produces ` +
        `a confident wrong answer. Finish setup for '${label}'.`,
    };
  }

  const { stale, ages } = stalenessOf(profile, todayISO, staleAfterDays);
  return { ok: true, label, profile, matchedBy, alsoMatched, stale, ages, staleAfterDays };
}

// ---- validation: closed key sets, never a look at any value ----------------

function checkCredential(credential, at, problems) {
  if (!isPlainObject(credential)) {
    problems.push({ path: at, problem: "must be an object" });
    return;
  }
  for (const key of Object.keys(credential)) {
    if (!CREDENTIAL_KEYS.has(key)) {
      problems.push({
        path: `${at}.${key}`,
        problem:
          `is not part of the credential schema (allowed: ${[...CREDENTIAL_KEYS].join(", ")}). There is no ` +
          `field for a credential VALUE anywhere in this file — reference it by env-var name.`,
      });
    }
  }
  if (credential.kind === CREDENTIAL_KIND.ENV_VAR) {
    if (!isEnvVarName(credential.name)) {
      problems.push({ path: `${at}.name`, problem: "must be an environment-variable name (letters, digits, underscore)" });
    }
  } else if (credential.kind === CREDENTIAL_KIND.PROVIDER_MANAGED) {
    if (credential.name !== undefined) {
      problems.push({ path: `${at}.name`, problem: "a provider-managed credential has no variable to name" });
    }
  } else {
    problems.push({
      path: `${at}.kind`,
      problem: `must be '${CREDENTIAL_KIND.ENV_VAR}' or '${CREDENTIAL_KIND.PROVIDER_MANAGED}'`,
    });
  }
}

function checkVerifiedBy(verifiedBy, at, problems) {
  if (!isPlainObject(verifiedBy)) {
    problems.push({ path: at, problem: "must be an object: {count} or {observedAt}, plus an optional note" });
    return;
  }
  for (const key of Object.keys(verifiedBy)) {
    if (!VERIFIED_BY_KEYS.has(key)) {
      problems.push({ path: `${at}.${key}`, problem: `is not part of the verifiedBy schema (allowed: ${[...VERIFIED_BY_KEYS].join(", ")})` });
    }
  }
  if (Object.keys(verifiedBy).length === 0) {
    problems.push({ path: at, problem: "is empty — record a count, an observedAt, or at minimum a note" });
  }
  if (verifiedBy.count !== undefined && !(Number.isInteger(verifiedBy.count) && verifiedBy.count >= 0)) {
    problems.push({ path: `${at}.count`, problem: "must be a non-negative integer" });
  }
  if (verifiedBy.observedAt !== undefined && !isISODate(verifiedBy.observedAt)) {
    problems.push({ path: `${at}.observedAt`, problem: "must be a calendar day, YYYY-MM-DD" });
  }
  if (verifiedBy.note !== undefined && typeof verifiedBy.note !== "string") {
    problems.push({ path: `${at}.note`, problem: "must be a string" });
  }
}

/**
 * Validate one connector. Returns `{ok}` or `{ok:false, problems:[{path, problem}]}`.
 *
 * Problems name the PATH and never the value, so a refusal can be printed and
 * logged without echoing whatever sat there.
 */
export function validateConnector(connector, at = "connector") {
  const problems = [];
  if (!isPlainObject(connector)) return { ok: false, problems: [{ path: at, problem: "must be an object" }] };

  for (const key of Object.keys(connector)) {
    if (!CONNECTOR_KEYS.has(key)) {
      problems.push({ path: `${at}.${key}`, problem: `is not part of the connector schema (allowed: ${[...CONNECTOR_KEYS].join(", ")})` });
    }
  }
  if (!isNonEmptyString(connector.via)) {
    problems.push({ path: `${at}.via`, problem: "must name what serves this capability" });
  }
  if (connector.scope !== undefined && !isPlainObject(connector.scope)) {
    problems.push({ path: `${at}.scope`, problem: "must be an object; its KEYS are your tool's own vocabulary" });
  }
  if (connector.howToQuery !== undefined) {
    const q = connector.howToQuery;
    if (!isPlainObject(q)) {
      problems.push({ path: `${at}.howToQuery`, problem: "must be structured: {tool, args[]}. It is documentation — the plugin never executes it" });
    } else {
      for (const key of Object.keys(q)) {
        if (!HOW_TO_QUERY_KEYS.has(key)) {
          problems.push({ path: `${at}.howToQuery.${key}`, problem: `is not part of the howToQuery schema (allowed: ${[...HOW_TO_QUERY_KEYS].join(", ")})` });
        }
      }
      if (!isNonEmptyString(q.tool)) problems.push({ path: `${at}.howToQuery.tool`, problem: "must be the tool name" });
      if (!isStringArray(q.args)) problems.push({ path: `${at}.howToQuery.args`, problem: "must be an array of strings — never one joined command string" });
    }
  }
  if (connector.credential !== undefined) checkCredential(connector.credential, `${at}.credential`, problems);
  if (connector.verifiedBy !== undefined) checkVerifiedBy(connector.verifiedBy, `${at}.verifiedBy`, problems);
  if (connector.verifiedAt !== undefined && !isISODate(connector.verifiedAt)) {
    problems.push({ path: `${at}.verifiedAt`, problem: "must be a calendar day, YYYY-MM-DD (day precision — millisecond precision guarantees merge conflicts)" });
  }
  return problems.length === 0 ? { ok: true } : { ok: false, problems };
}

function checkProfile(profile, at, problems) {
  if (!isPlainObject(profile)) {
    problems.push({ path: at, problem: "must be an object" });
    return;
  }
  for (const key of Object.keys(profile)) {
    if (!PROFILE_KEYS.has(key)) {
      problems.push({ path: `${at}.${key}`, problem: `is not part of the profile schema (allowed: ${[...PROFILE_KEYS].join(", ")})` });
    }
  }
  if (profile.buildMatch !== undefined) {
    if (!isStringArray(profile.buildMatch)) {
      problems.push({ path: `${at}.buildMatch`, problem: "must be an array of build-NAME patterns" });
    } else {
      profile.buildMatch.forEach((pattern, i) => {
        if (pattern.trim() === "") {
          problems.push({ path: `${at}.buildMatch[${i}]`, problem: "is empty" });
          return;
        }
        let stars = 0;
        for (const ch of pattern) if (ch === "*") stars++;
        if (stars > 1) {
          problems.push({
            path: `${at}.buildMatch[${i}]`,
            problem: "has more than one '*'. Matching supports exactly one wildcard, so a second one could only be guessed at",
          });
        }
      });
    }
  }
  if (profile.repos !== undefined) {
    if (!isPlainObject(profile.repos)) {
      problems.push({ path: `${at}.repos`, problem: "must be an object keyed by ROLE (product / automation), not a flat list" });
    } else {
      for (const [role, list] of Object.entries(profile.repos)) {
        if (!REPO_ROLES.has(role)) {
          problems.push({ path: `${at}.repos.${role}`, problem: `is not a known repo role (allowed: ${[...REPO_ROLES].join(", ")})` });
        }
        if (!isStringArray(list)) problems.push({ path: `${at}.repos.${role}`, problem: "must be an array of org/repo strings" });
      }
    }
  }
  // `null` is meaningful and must survive: with no owned subpaths, path overlap
  // runs repo-wide, and the hunt has to be able to SAY that instead of
  // over-attributing a PR from an unrelated package in the same monorepo.
  if (profile.subpaths !== undefined && profile.subpaths !== null && !isStringArray(profile.subpaths)) {
    problems.push({ path: `${at}.subpaths`, problem: "must be an array of paths, or null to mean 'repo-wide, attribution may over-match'" });
  }
  if (profile.branches !== undefined) {
    if (!isPlainObject(profile.branches)) {
      problems.push({ path: `${at}.branches`, problem: "must be an object: {default, observed[]}" });
    } else {
      for (const key of Object.keys(profile.branches)) {
        if (!BRANCH_KEYS.has(key)) {
          problems.push({ path: `${at}.branches.${key}`, problem: `is not part of the branches schema (allowed: ${[...BRANCH_KEYS].join(", ")})` });
        }
      }
      if (profile.branches.default !== undefined && !isNonEmptyString(profile.branches.default)) {
        problems.push({ path: `${at}.branches.default`, problem: "must be a branch name" });
      }
      if (profile.branches.observed !== undefined && !isStringArray(profile.branches.observed)) {
        problems.push({ path: `${at}.branches.observed`, problem: "must be an array of branch names" });
      }
    }
  }
  if (profile.connectors !== undefined) {
    if (!isPlainObject(profile.connectors)) {
      problems.push({ path: `${at}.connectors`, problem: "must be an object keyed by capability" });
    } else {
      for (const [capability, connector] of Object.entries(profile.connectors)) {
        const r = validateConnector(connector, `${at}.connectors.${capability}`);
        if (!r.ok) problems.push(...r.problems);
      }
    }
  }
  for (const key of ["gaps", "warnings"]) {
    if (profile[key] === undefined) continue;
    if (!Array.isArray(profile[key])) {
      problems.push({ path: `${at}.${key}`, problem: "must be an array" });
      continue;
    }
    profile[key].forEach((entry, i) => {
      if (typeof entry === "string") return;
      if (!isPlainObject(entry)) {
        problems.push({ path: `${at}.${key}[${i}]`, problem: "must be a string or an object naming a capability" });
        return;
      }
      for (const k of Object.keys(entry)) {
        if (!GAP_KEYS.has(k)) {
          problems.push({ path: `${at}.${key}[${i}].${k}`, problem: `is not part of the ${key} schema (allowed: ${[...GAP_KEYS].join(", ")})` });
        }
      }
      if (!isNonEmptyString(entry.capability)) {
        problems.push({ path: `${at}.${key}[${i}].capability`, problem: "must name the capability it covers, or nothing can tell whether that capability was answered" });
      }
    });
  }
}

/**
 * Validate a whole document. Structure only — this never inspects a value to
 * decide what it "looks like".
 */
export function validateContext(context) {
  const problems = [];
  if (!isPlainObject(context)) return { ok: false, problems: [{ path: "(root)", problem: "must be an object" }] };

  for (const key of Object.keys(context)) {
    if (!CONTEXT_KEYS.has(key)) {
      problems.push({ path: key, problem: `is not part of the context schema (allowed: ${[...CONTEXT_KEYS].join(", ")})` });
    }
  }
  for (const field of REQUIRED_FIELDS) {
    if (context[field] === undefined) problems.push({ path: field, problem: "is required" });
  }
  if (context.schemaVersion !== undefined && context.schemaVersion !== SCHEMA_VERSION) {
    problems.push({ path: "schemaVersion", problem: `must be ${SCHEMA_VERSION}; this plugin writes only that version` });
  }
  if (context.homeRepo !== undefined && !isNonEmptyString(context.homeRepo)) {
    problems.push({ path: "homeRepo", problem: "must name the repo this file is committed to, as org/repo" });
  }
  if (context._README !== undefined && typeof context._README !== "string") {
    problems.push({ path: "_README", problem: "must be a string" });
  }
  if (context.profiles !== undefined) {
    if (!isPlainObject(context.profiles) || Object.keys(context.profiles).length === 0) {
      problems.push({ path: "profiles", problem: "must be a non-empty object of labelled profiles" });
    } else {
      for (const [label, profile] of Object.entries(context.profiles)) {
        if (label.trim() === "") problems.push({ path: "profiles", problem: "has an empty profile label" });
        checkProfile(profile, `profiles.${label}`, problems);
      }
    }
  }
  if (context.defaultProfile !== undefined) {
    if (!isNonEmptyString(context.defaultProfile)) {
      problems.push({ path: "defaultProfile", problem: "must be a profile label" });
    } else if (isPlainObject(context.profiles) && !Object.hasOwn(context.profiles, context.defaultProfile)) {
      problems.push({ path: "defaultProfile", problem: `names '${context.defaultProfile}', which is not a profile in this file` });
    }
  }
  return problems.length === 0 ? { ok: true } : { ok: false, problems };
}

// ---- filesystem resolution -------------------------------------------------

/** Canonical form of a path, so the read side and the write side never disagree
 *  about the same file. `git rev-parse --show-toplevel` always reports a
 *  realpath, while a directory walk reports whatever it was handed — and on
 *  macOS `/var` is a symlink to `/private/var`, so the two differ for every
 *  temp-dir path. */
function canonical(p) {
  try {
    return realpathSync(p);
  } catch {
    return resolve(p);
  }
}

/** The ONLY child_process use in this module: git, argv-only, never a shell. */
function git(dir, args) {
  return execFileSync("git", ["-C", dir, ...args], {
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function gitTry(dir, args) {
  try {
    return { ok: true, out: git(dir, args) };
  } catch (err) {
    return { ok: false, status: err?.status ?? null };
  }
}

/**
 * `git check-ignore -v` exits 0 when the path IS ignored and 1 when it is not, so
 * a throw is the ordinary "not ignored" answer. But only exit 1 means that: a
 * bare catch also swallows exit 128 (corrupt index, unreadable excludes, broken
 * worktree) and reports it as "not ignored", letting a write proceed on the
 * strength of a question git never answered.
 */
function ignoreRuleFor(dir, relPath) {
  try {
    const out = git(dir, ["check-ignore", "-v", "--", relPath]);
    return { ignored: true, rule: out.trim() || "an unnamed .gitignore rule" };
  } catch (err) {
    if (err?.status === 1) return { ignored: false };
    return { error: err?.status === undefined ? "git could not be run" : `git exited ${err.status}` };
  }
}

/** Is this file tracked by the repo it sits in? A committed context is tracked by
 *  construction — that is the entire point of committing it — so this separates
 *  an inherited context from a file that merely happens to share the name. */
function isTracked(dir, relPath) {
  return gitTry(dir, ["ls-files", "--error-unmatch", "--", relPath]).ok;
}

/** Does this worktree's origin remote name `homeRepo`? The directory-name check
 *  alone refuses a repo cloned under a different name, a renamed repo, and every
 *  linked worktree. */
function originNames(dir, homeRepo) {
  const r = gitTry(dir, ["remote", "get-url", "origin"]);
  if (!r.ok) return false;
  let url = r.out.trim();
  if (url.endsWith(".git")) url = url.slice(0, -4);
  const slug = trimChar(String(homeRepo ?? ""), "/");
  if (slug === "") return false;
  return url.endsWith(`/${slug}`) || url.endsWith(`:${slug}`);
}

function worktreeRoot(dir) {
  const r = gitTry(dir, ["rev-parse", "--show-toplevel"]);
  if (!r.ok) return null;
  const root = r.out.trim();
  return root ? canonical(root) : null;
}

/** Immediate child directories, symlinked clones included. */
function childDirs(dir) {
  try {
    return readdirSync(dir, { withFileTypes: true })
      .filter((e) => !e.name.startsWith("."))
      .filter((e) => {
        if (e.isDirectory()) return true;
        if (!e.isSymbolicLink()) return false;
        try {
          return statSync(join(dir, e.name)).isDirectory();
        } catch {
          return false;
        }
      })
      .map((e) => join(dir, e.name));
  } catch {
    return [];
  }
}

/**
 * Bounded candidates: each level from `from` upward, plus that level's immediate
 * children. The children half is what makes a sibling layout work — clones sit
 * side by side under a workspace root, so a context committed to the product repo
 * is invisible from the automation repo if you only walk upward, and the
 * no-context refusal would then fire on a fully set-up machine.
 *
 * Canonicalisation is deliberately not done here: the walk yields ~140
 * candidates and all but one are discarded, so realpath'ing every one lstats
 * every component of a directory nobody will look at.
 */
function candidateDirs(from) {
  const out = new Set();
  let dir = resolve(from);
  for (let level = 0; level < MAX_LEVELS; level++) {
    out.add(dir);
    for (const child of childDirs(dir)) out.add(child);
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return [...out];
}

function homeRepoMatches(dir, homeRepo) {
  return basename(dir) === basename(String(homeRepo ?? ""));
}

/**
 * Locate the context and return its already-read bytes plus how strongly it is
 * tied to this machine.
 *
 * Adoption is applied BEFORE anything the file says about itself. The walk covers
 * ~140 directories, and `homeRepo` is a value the FILE supplies — so testing only
 * "does this directory's name match the homeRepo it declares" adopts any
 * `.rca-context.json` in any repo cloned nearby, and that file then drives the
 * run's repos, branches and scope.
 *
 * Two things are trustworthy: the worktree we were actually invoked from, and a
 * file the repo it sits in TRACKS. A real inherited context is committed by
 * design, so an untracked file in a sibling clone is neither and is skipped
 * outright.
 */
function locateContext({ from = process.cwd(), pluginRoot = null } = {}) {
  const forbidden = pluginRoot ? canonical(pluginRoot) : null;
  const ownRoot = worktreeRoot(from);

  for (const dir of candidateDirs(from)) {
    const path = join(dir, CONTEXT_FILENAME);
    let raw;
    try {
      raw = readFileSync(path, "utf8");
    } catch {
      continue; // absent or unreadable — try the next candidate
    }
    const canon = canonical(dir);
    // The documented install flow is `git clone <plugin> && cd <plugin> &&
    // claude --plugin-dir ./`, so cwd IS the plugin root on first contact. A
    // context there is inherited by nobody, so it is never read and never
    // written.
    if (forbidden && canon === forbidden) continue;

    const isOwnWorktree = ownRoot !== null && canon === ownRoot;
    let trust = "own-worktree";
    if (!isOwnWorktree) {
      const root = worktreeRoot(dir);
      if (root === null || root !== canon) continue; // not a worktree ROOT
      if (!isTracked(dir, CONTEXT_FILENAME)) continue; // planted, not inherited
      trust = "tracked";
    }

    let parsed;
    try {
      parsed = JSON.parse(raw);
    } catch {
      // A file that is there but unparseable is still THE context: returning it
      // lets readRcaContext report a parse error rather than walking past it and
      // reporting "no context", which would silently trigger a fresh interview
      // and look like the feature forgetting the customer.
      //
      // This sits BELOW the adoption test on purpose. Above it, any junk
      // .rca-context.json anywhere in the walk short-circuits the search and
      // every run refuses — a denial of service from any writable directory near
      // the repo.
      return { path: join(canon, CONTEXT_FILENAME), raw, trust };
    }
    if (originNames(dir, parsed?.homeRepo)) {
      return { path: join(canon, CONTEXT_FILENAME), raw, trust: isOwnWorktree ? "own-worktree" : "origin-match" };
    }
    if (homeRepoMatches(dir, parsed?.homeRepo)) {
      return { path: join(canon, CONTEXT_FILENAME), raw, trust: isOwnWorktree ? "own-worktree" : "tracked" };
    }
  }
  return null;
}

/** The context file's path, or null. */
export function findContextFile({ from = process.cwd(), pluginRoot = null } = {}) {
  return locateContext({ from, pluginRoot })?.path ?? null;
}

/**
 * Read and validate the context.
 *
 * Fails LOUD on drift. Unparseable, wrong-version and invalid-schema are distinct
 * named errors and never a silent fall-through to "no context": telling someone
 * to re-run the interview when their file is merely conflict-marked throws away
 * every answer they already gave.
 */
export function readRcaContext({ from = process.cwd(), pluginRoot = null, path = null } = {}) {
  let file = path;
  let raw;
  let trust = path === null ? null : "caller-supplied";
  if (file === null) {
    const found = locateContext({ from, pluginRoot });
    if (!found) return { ok: false, code: "no-context", message: `no ${CONTEXT_FILENAME} found near ${resolve(from)}` };
    ({ path: file, raw } = found);
    trust = found.trust ?? null;
  } else {
    try {
      raw = readFileSync(file, "utf8");
    } catch (err) {
      return { ok: false, code: "unreadable", path: file, message: `cannot read ${file}: ${err?.code ?? "error"}` };
    }
  }

  let context;
  try {
    context = JSON.parse(raw);
  } catch (err) {
    return {
      ok: false,
      code: "parse-error",
      path: file,
      message:
        `${file} is not valid JSON (${String(err?.message ?? "").split("\n")[0]}). If this is a merge ` +
        `conflict, resolve it — it is deliberately NOT treated as a missing context, so nothing you ` +
        `already answered is lost.`,
    };
  }

  if (context?.schemaVersion !== undefined && context.schemaVersion !== SCHEMA_VERSION) {
    return {
      ok: false,
      code: "schema-version",
      path: file,
      found: context.schemaVersion,
      expected: SCHEMA_VERSION,
      message: `${file} declares schemaVersion ${context.schemaVersion}, but this plugin expects ${SCHEMA_VERSION}.`,
    };
  }

  const valid = validateContext(context);
  if (!valid.ok) {
    const missing = valid.problems.filter((p) => p.problem === "is required").map((p) => p.path);
    return {
      ok: false,
      code: missing.length > 0 ? "missing-field" : "invalid-context",
      path: file,
      fields: missing,
      problems: valid.problems,
      message:
        `${file} does not match the context schema: ` +
        `${valid.problems.map((p) => `${p.path} ${p.problem}`).join("; ")}`,
    };
  }

  return { ok: true, context, path: file, raw, trust };
}

/**
 * Where the context belongs: the working-tree root of the repo it declares as
 * `homeRepo`.
 *
 * Read-side resolution does not prevent a bad write. The install flow puts cwd
 * inside the plugin, so a first run that simply wrote next to cwd would land the
 * file where no teammate inherits it.
 */
export function contextHomeDir({ homeRepo, from = process.cwd(), pluginRoot = null } = {}) {
  if (!isNonEmptyString(homeRepo)) {
    return { ok: false, code: "no-home-repo", message: "the context declares no homeRepo, so there is nowhere to write it" };
  }
  const forbidden = pluginRoot ? canonical(pluginRoot) : null;
  const allowed = (dir) => !(forbidden && canonical(dir) === forbidden);

  // Fast path: the clone directory is named after the repo.
  for (const dir of candidateDirs(from)) {
    if (!homeRepoMatches(dir, homeRepo)) continue;
    if (!allowed(dir)) continue;
    const root = worktreeRoot(dir);
    if (root && allowed(root)) return { ok: true, dir: root, matchedBy: "directory-name" };
  }

  // Fallback: ask git instead of the directory name. A basename-only match
  // refuses a repo cloned under a different name, a renamed repo, and every
  // linked worktree — after the whole interview has already succeeded, with a
  // next action the customer has by definition already taken.
  const seen = new Set();
  for (const dir of [resolve(from), ...candidateDirs(from)]) {
    if (!allowed(dir)) continue;
    const root = worktreeRoot(dir);
    if (!root || seen.has(root) || !allowed(root)) continue;
    seen.add(root);
    if (originNames(root, homeRepo)) return { ok: true, dir: root, matchedBy: "origin-remote" };
  }

  return {
    ok: false,
    code: "no-git-worktree",
    message:
      `could not find a git working tree for '${homeRepo}' near ${resolve(from)}. Run this from inside ` +
      `the repository the context should be committed to.`,
  };
}

/**
 * Would this write lose something the file already records?
 *
 * Writes are per-connector and additive by design, which is what makes an
 * abandoned interview resumable for free. So the guard is not "is the new
 * document valid" but "does it still contain everything the old one proved":
 * dropping a profile, dropping a connector, or replacing a connector whose
 * verifiedBy carried a count/observedAt with one that carries neither.
 */
function regressions(existing, next) {
  const problems = [];
  if (!isPlainObject(existing?.profiles)) return problems;
  for (const [label, profile] of Object.entries(existing.profiles)) {
    const after = next?.profiles?.[label];
    if (!isPlainObject(after)) {
      problems.push({ path: `profiles.${label}`, problem: "would be dropped" });
      continue;
    }
    for (const [capability, connector] of Object.entries(profile?.connectors ?? {})) {
      const nextConnector = after.connectors?.[capability];
      if (!isPlainObject(nextConnector)) {
        problems.push({ path: `profiles.${label}.connectors.${capability}`, problem: "would be dropped" });
        continue;
      }
      if (isVerifiedClaim(connector.verifiedBy) && !isVerifiedClaim(nextConnector.verifiedBy)) {
        problems.push({
          path: `profiles.${label}.connectors.${capability}.verifiedBy`,
          problem: "would be replaced by one carrying neither a count nor an observedAt, which proves nothing",
        });
      }
    }
  }
  return problems;
}

/** Temp file in the SAME directory, then rename — atomic on POSIX, so a torn or
 *  refused write leaves the committed file byte-identical. No mode, no chmod:
 *  git tracks this path. */
function atomicWrite(path, body) {
  const tmp = `${path}.${process.pid}.tmp`;
  try {
    writeFileSync(tmp, body, "utf8");
    renameSync(tmp, path);
  } catch (err) {
    try {
      unlinkSync(tmp);
    } catch { /* nothing to clean up */ }
    return { ok: false, code: "write-failed", path, message: `could not write ${path}: ${err?.code ?? "unknown error"}. Check permissions and free space.` };
  }
  return { ok: true, path };
}

function serialize(context) {
  return `${JSON.stringify(context, null, 2)}\n`;
}

/**
 * Persist a whole document. Used to CREATE the file; every later change should go
 * through upsertConnector or recordGap, which are additive by construction.
 */
export function writeRcaContext({ context, from = process.cwd(), pluginRoot = null, path = null } = {}) {
  const valid = validateContext(context);
  if (!valid.ok) {
    return {
      ok: false,
      code: "invalid-context",
      problems: valid.problems,
      // Paths, never values: a refusal is printed and logged, and whatever sat in
      // the offending field must not be echoed into a transcript.
      message: `refusing to write: ${valid.problems.map((p) => `${p.path} ${p.problem}`).join("; ")}`,
    };
  }

  let target = path;
  if (target === null) {
    const home = contextHomeDir({ homeRepo: context.homeRepo, from, pluginRoot });
    if (!home.ok) return home;
    target = join(home.dir, CONTEXT_FILENAME);
  }
  const dir = dirname(target);

  const ignore = ignoreRuleFor(dir, CONTEXT_FILENAME);
  if (ignore.error) {
    return {
      ok: false,
      code: "ignore-check-failed",
      path: target,
      message: `could not determine whether ${target} is git-ignored (${ignore.error}). Refusing rather than writing a file that may never be committed.`,
    };
  }
  if (ignore.ignored) {
    return {
      ok: false,
      code: "ignored-destination",
      path: target,
      rule: ignore.rule,
      message: `${target} is excluded by ${ignore.rule}, so it would never be committed and no teammate would inherit it. Narrow the rule, or choose a different home repo.`,
    };
  }

  let existing = null;
  try {
    existing = JSON.parse(readFileSync(target, "utf8"));
  } catch { /* absent or unparseable — the regression guard has nothing to compare */ }

  const lost = regressions(existing, context);
  if (lost.length > 0) {
    return {
      ok: false,
      code: "would-regress",
      path: target,
      problems: lost,
      message:
        `refusing to write ${target}: ${lost.map((p) => `${p.path} ${p.problem}`).join("; ")}. Writes here ` +
        `are additive — a teammate's verified connector is not this run's to discard.`,
    };
  }

  return atomicWrite(target, serialize(context));
}

/** Structural clone via JSON, which is exactly the value space this file holds.
 *  Untouched branches keep their key order, so an unrelated connector
 *  re-serializes byte-identically. */
function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

/**
 * Write ONE connector into ONE profile.
 *
 * Per-connector and additive, the moment each capability verifies — not once at
 * the end. Abandonment then persists progress for free, with no partial-state
 * machinery at all, and the mandatory capability being asked first means the
 * common abandonment leaves a runnable profile.
 */
export function upsertConnector({
  capability,
  connector,
  profile: label = null,
  todayISO = null,
  from = process.cwd(),
  pluginRoot = null,
  path = null,
} = {}) {
  if (!isNonEmptyString(capability)) {
    return { ok: false, code: "no-capability", message: "name the capability this connector serves" };
  }
  const read = readRcaContext({ from, pluginRoot, path });
  if (!read.ok) return read;

  const labels = Object.keys(read.context.profiles);
  const target = isNonEmptyString(label) ? label.trim() : labels.length === 1 ? labels[0] : null;
  if (target === null) {
    return {
      ok: false,
      code: "no-profile",
      labels,
      message: `this context holds ${labels.length} profiles (${labels.join(", ")}); name the one to write into`,
    };
  }
  if (!Object.hasOwn(read.context.profiles, target)) {
    return { ok: false, code: "unknown-profile", labels, message: `no profile named '${target}' (have: ${labels.join(", ")})` };
  }

  const staged = clone(connector ?? null);
  if (isPlainObject(staged) && staged.verifiedAt === undefined && isISODate(todayISO)) {
    staged.verifiedAt = todayISO.slice(0, 10);
  }
  const shape = validateConnector(staged, `profiles.${target}.connectors.${capability}`);
  if (!shape.ok) {
    return {
      ok: false,
      code: "invalid-connector",
      problems: shape.problems,
      message: `refusing to write: ${shape.problems.map((p) => `${p.path} ${p.problem}`).join("; ")}`,
    };
  }

  const next = clone(read.context);
  if (!isPlainObject(next.profiles[target].connectors)) next.profiles[target].connectors = {};
  next.profiles[target].connectors[capability] = staged;

  const result = writeRcaContext({ context: next, from, pluginRoot, path: read.path });
  if (!result.ok) return result;
  return {
    ok: true,
    path: result.path,
    profile: target,
    capability,
    verified: isVerifiedClaim(staged.verifiedBy),
    runnable: isRunnable(next.profiles[target]),
  };
}

/**
 * Record a capability as un-answered, on purpose.
 *
 * This is the write that makes `provisioned` reachable: a skipped or failed
 * capability gets a gap, so the gate's one question is asked once rather than
 * every run, and the resume walk never re-asks something the customer already
 * declined.
 */
/**
 * Append a gap or a warning to a profile. One implementation, two verbs.
 *
 * Both are additive and both are idempotent on (capability, classification): a
 * re-run replaces the matching entry rather than growing the list, so a resumed
 * interview does not accumulate duplicates.
 *
 * `warnings` needed a writer at all because the gate is told to PRINT them
 * (`templates/gate-summary.md`) and the only other way to add one was to rewrite the
 * whole document by hand — which is what this CLI exists to prevent. Without it the
 * empty-PR-window warning could only ever be recorded during the interview's first
 * write, and would freeze there.
 *
 * The two share a schema deliberately: a warning IS a gap that does not degrade
 * evidence. `{capability, classification, note?, target?}` for both, so a reader
 * needs one shape, not two.
 */
function recordEntry({
  kind,
  capability,
  classification,
  note = null,
  target: entryTarget = null,
  profile: label = null,
  from = process.cwd(),
  pluginRoot = null,
  path = null,
}) {
  const noun = kind === "warnings" ? "warning" : "gap";
  if (!isNonEmptyString(capability)) {
    return { ok: false, code: "no-capability", message: `name the capability this ${noun} covers` };
  }
  if (!isNonEmptyString(classification)) {
    return {
      ok: false,
      code: "no-classification",
      message:
        kind === "warnings"
          ? "classify the warning (e.g. empty-pr-window) — an unclassified warning cannot be acted on or suppressed"
          : "classify the gap (e.g. declined, absent-on-this-machine, credential-under-scoped-for-target) — an unclassified gap tells the next run nothing",
    };
  }
  const read = readRcaContext({ from, pluginRoot, path });
  if (!read.ok) return read;

  const labels = Object.keys(read.context.profiles);
  const profileLabel = isNonEmptyString(label) ? label.trim() : labels.length === 1 ? labels[0] : null;
  if (profileLabel === null) {
    return { ok: false, code: "no-profile", labels, message: `this context holds ${labels.length} profiles (${labels.join(", ")}); name the one to write into` };
  }
  if (!Object.hasOwn(read.context.profiles, profileLabel)) {
    return { ok: false, code: "unknown-profile", labels, message: `no profile named '${profileLabel}' (have: ${labels.join(", ")})` };
  }

  const next = clone(read.context);
  const profile = next.profiles[profileLabel];
  if (!Array.isArray(profile[kind])) profile[kind] = [];
  const entry = { capability, classification };
  if (isNonEmptyString(note)) entry.note = note;
  if (isNonEmptyString(entryTarget)) entry.target = entryTarget;

  const already = profile[kind].findIndex(
    (g) => (isPlainObject(g) ? g.capability : g) === capability && (isPlainObject(g) ? g.classification : null) === classification,
  );
  if (already >= 0) profile[kind][already] = entry;
  else profile[kind].push(entry);

  const result = writeRcaContext({ context: next, from, pluginRoot, path: read.path });
  if (!result.ok) return result;
  return { ok: true, path: result.path, profile: profileLabel, capability, classification };
}

/** A capability that will not be gathered. Degrades evidence; declared to TFA. */
export function recordGap(opts = {}) {
  return recordEntry({ ...opts, kind: "gaps" });
}

/** A capability that WORKS but whose result predicts a thin answer — an empty
 *  PR window being the case this exists for. Printed at the gate; never a gap,
 *  because the capability is reachable and nothing is wrong with it. */
export function recordWarning(opts = {}) {
  return recordEntry({ ...opts, kind: "warnings" });
}
